#!/bin/bash
BASEDIR=$(dirname $0)
MODE="$1"

cd $BASEDIR
cd ..

# Check if the directory ../misc/ exists
misctest="misc"
if [ -d "$misctest" ]
then
   echo "misc/ exists!"
	 cp misc/* .
else
   echo "misc/ does not exist! Making..."
   mkdir "$misctest"
fi

# Build the dissertation.
if [ "$MODE" == "all" ]; then
	xelatex tesi
	bibtex tesi
	xelatex tesi
	xelatex tesi
else
	xelatex tesi
fi

# Move temp files
ls *.aux *.bbl *.blg *.toc *.lot *.lof *.log *.lol *.out | xargs -I {} mv {} misc/
